### ISSUE TITLE
multipart/form-data causing exception to be thrown in core.py

### ISSUE THREAD

**Issue by GabrielPerry** [requests/requests-oauthlib#31]
In the file: core.py, the following line of code causes a TypeError Exception to be thrown when you are trying to send a multipart data post request.

The error message that I'm seeing is: TypeError: Type str doesn't support the buffer API

Here's the problematic line of code in core.py:

```
is_form_encoded = (CONTENT_TYPE_FORM_URLENCODED in headers.get('Content-Type', ''))
```

Use-case: When sending a POST request (with the Requests API) using the "files" parameter like so:

```
response = requests.request(method='POST', url=api_url, auth=self.oauth, params=params, files=file_payload)
```

When this call makes its way down to core.py, Python3.3 is not happy.  Why?  It appears the "in" operator in the above statement (in core.py) performs a problematic comparison.  r.headers.get('Content-Type', '') returns a byte-stream instead of a string when multipart data is being sent from the Requests API.   CONTENT_TYPE_FORM_URLENCODED, however, is a 'str' type.  This comparison causes a TypeError exception to be thrown.

Here's a hack I implemented to get around this problem:

```
    #-----------------------------------------------------------------------
    #
    # SketchUp modified code starts here.
    content_type = r.headers.get('Content-Type', '')
    try:
        if (CONTENT_TYPE_FORM_URLENCODED in content_type):
            is_form_encoded = True
        else:
            is_form_encoded = False
    except Exception as e:
        # print("OAuth BUG: comparing 'byte stream' with 'str' type when "
        #       "a multipart request header is encountered.")
        is_form_encoded = False
    #
    # SketchUp modified code ends here.
    #-----------------------------------------------------------------------

    #-----------------------------------------------------------------------
    # This is the OAuth block of code that SketchUp has commented out:
    #
    # is_form_encoded = (CONTENT_TYPE_FORM_URLENCODED in
    #         r.headers.get('Content-Type', ''))
    #
    #-----------------------------------------------------------------------
```

I think you should be aware of this issue as it caused me some serious pain.  My "fix" is just a hack and I'm sure there's a better way to solve this problem.

~Gabriel
